----GO
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (1, N'eng', N'English')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (2, N'en-US', N'United States English')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (3, N'fre', N'French')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (4, N'spa', N'Spanish')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (5, N'en-GB', N'British English')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (6, N'mul', N'Multiple Languages')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (7, N'grc', N'Greek')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (8, N'enm', N'Middle English')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (9, N'en-CA', N'Canadian English')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (10, N'ger', N'German')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (11, N'jpn', N'Japanese')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (12, N'ara', N'Arabic')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (13, N'nl', N'Dutch')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (14, N'zho', N'Chinese')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (15, N'lat', N'Latin')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (16, N'por', N'Portuguese')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (17, N'srp', N'Serbian')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (18, N'ita', N'Italian')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (19, N'rus', N'Russian')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (20, N'msa', N'Malaysian')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (21, N'glg', N'Galician')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (22, N'wel', N'Welsh')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (23, N'swe', N'Swedish')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (24, N'nor', N'Norwegian')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (25, N'tur', N'Turkish')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (26, N'gla', N'Gaelic')
INSERT [dbo].[book_language] ([language_id], [language_code], [language_name]) VALUES (27, N'ale', N'Aleut')
