--GO
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (1, N'Afghanistan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (2, N'Netherlands Antilles')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (3, N'Albania')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (4, N'Algeria')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (5, N'Andorra')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (6, N'Angola')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (7, N'Antigua and Barbuda')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (8, N'Australasia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (9, N'Argentina')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (10, N'Armenia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (11, N'Aruba')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (12, N'American Samoa')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (13, N'Australia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (14, N'Austria')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (15, N'Azerbaijan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (16, N'Bahamas')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (17, N'Bangladesh')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (18, N'Barbados')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (19, N'Burundi')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (20, N'Belgium')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (21, N'Benin')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (22, N'Bermuda')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (23, N'Bhutan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (24, N'Bosnia and Herzegovina')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (25, N'Belize')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (26, N'Belarus')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (27, N'Bohemia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (28, N'Boliva')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (29, N'Botswana')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (30, N'Brazil')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (31, N'Bahrain')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (32, N'Brunei')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (33, N'Bulgaria')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (34, N'Burkina Faso')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (35, N'Central African Republic')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (36, N'Cambodia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (37, N'Canada')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (38, N'Cayman Islands')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (39, N'Republic of Congo')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (40, N'Chad')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (41, N'Chile')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (42, N'China')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (43, N'Ivory Coast')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (44, N'Cameroon')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (45, N'Democratic Republic of the Congo')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (46, N'Cook Islands')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (47, N'Colombia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (48, N'Comoros')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (49, N'Cape Verde')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (50, N'Costa Rica')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (51, N'Croatia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (52, N'Crete')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (53, N'Cuba')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (54, N'Cyprus')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (55, N'Czech Republic')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (56, N'Denmark')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (57, N'Djibouti')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (58, N'Dominica')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (59, N'Dominican Republic')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (60, N'Ecuador')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (61, N'Egypt')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (62, N'Eritrea')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (63, N'El Salvador')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (64, N'Spain')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (65, N'Estonia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (66, N'Ethiopia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (67, N'Unified Team')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (68, N'Fiji')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (69, N'Finland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (70, N'France')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (71, N'West Germany')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (72, N'Micronesia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (73, N'Gabon')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (74, N'Gambia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (75, N'United Kingdom')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (76, N'Guinea-Bissau')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (77, N'East Germany')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (78, N'Georgia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (79, N'Equatorial Guinea')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (80, N'Germany')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (81, N'Ghana')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (82, N'Greece')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (83, N'Grenada')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (84, N'Guatemala')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (85, N'Guinea')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (86, N'Guam')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (87, N'Guyana')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (88, N'Haiti')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (89, N'Hong Kong')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (90, N'Honduras')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (91, N'Hungary')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (92, N'Indonesia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (93, N'India')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (94, N'Individual Olympic Athletes')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (95, N'Iran')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (96, N'Ireland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (97, N'Iraq')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (98, N'Iceland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (99, N'Israel')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (100, N'Virgin Islands')
--GO
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (101, N'Italy')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (102, N'Virgin Islands, British')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (103, N'Jamaica')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (104, N'Jordan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (105, N'Japan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (106, N'Kazakhstan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (107, N'Kenya')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (108, N'Kyrgyzstan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (109, N'Kiribati')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (110, N'South Korea')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (111, N'Kosovo')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (112, N'Saudi Arabia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (113, N'Kuwait')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (114, N'Laos')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (115, N'Latvia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (116, N'Libya')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (117, N'Liberia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (118, N'Saint Lucia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (119, N'Lesotho')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (120, N'Lebanon')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (121, N'Liechtenstein')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (122, N'Lithuania')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (123, N'Luxembourg')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (124, N'Madagascar')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (125, N'Malaya')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (126, N'Morocco')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (127, N'Malaysia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (128, N'Malawi')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (129, N'Moldova')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (130, N'Maldives')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (131, N'Mexico')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (132, N'Mongolia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (133, N'Marshall Islands')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (134, N'Macedonia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (135, N'Mali')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (136, N'Malta')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (137, N'Montenegro')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (138, N'Monaco')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (139, N'Mozambique')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (140, N'Mauritius')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (141, N'Mauritania')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (142, N'Myanmar')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (143, N'Namibia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (144, N'North Borneo')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (145, N'Nicaragua')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (146, N'Netherlands')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (147, N'Nepal')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (148, N'Newfoundland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (149, N'Nigeria')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (150, N'Niger')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (151, N'Norway')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (152, N'Nauru')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (153, N'New Zealand')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (154, N'Oman')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (155, N'Pakistan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (156, N'Panama')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (157, N'Paraguay')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (158, N'Peru')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (159, N'Philippines')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (160, N'Palestine')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (161, N'Palau')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (162, N'Papua New Guinea')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (163, N'Poland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (164, N'Portugal')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (165, N'North Korea')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (166, N'Puerto Rico')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (167, N'Qatar')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (168, N'Zimbabwe (Rhodesia)')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (169, N'Refugee Olympic Team')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (170, N'Romania')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (171, N'South Africa')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (172, N'Russia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (173, N'Rwanda')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (174, N'Saar')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (175, N'Samoa')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (176, N'Serbia and Montenegro')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (177, N'Senegal')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (178, N'Seychelles')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (179, N'Singapore')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (180, N'Turks and Caicos Islands')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (181, N'Sierra Leone')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (182, N'Slovenia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (183, N'San Marino')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (184, N'Solomon Islands')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (185, N'Somalia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (186, N'Serbia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (187, N'Sri Lanka')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (188, N'South Sudan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (189, N'Sao Tome and Principe')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (190, N'Sudan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (191, N'Switzerland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (192, N'Suriname')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (193, N'Slovakia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (194, N'Sweden')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (195, N'Swaziland')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (196, N'Syria')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (197, N'Tanzania')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (198, N'Czechoslovakia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (199, N'Tonga')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (200, N'Thailand')
--GO
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (201, N'Tajikistan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (202, N'Turkmenistan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (203, N'Timor-Leste')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (204, N'Togo')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (205, N'Taiwan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (206, N'Trinidad and Tobago')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (207, N'Tunisia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (208, N'Turkey')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (209, N'Tuvalu')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (210, N'United Arab Emirates')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (211, N'United Arab Republic')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (212, N'Uganda')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (213, N'Ukraine')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (214, N'Unknown')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (215, N'Soviet Union')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (216, N'Uruguay')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (217, N'United States of America')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (218, N'Uzbekistan')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (219, N'Vanuatu')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (220, N'Venezuela')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (221, N'Vietnam')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (222, N'Saint Vincent')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (223, N'Vietnam (pre)')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (224, N'West Indies Federation')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (225, N'North Yemen')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (226, N'Yemen')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (227, N'South Yemen')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (228, N'Yugoslavia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (229, N'Zambia')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (230, N'Zimbabwe')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (231, N'Singapore')
INSERT [dbo].[country] ([country_id], [country_name]) VALUES (232, N'French Polynesia')
